name: dot_coaching
description: "Dot Coaching Mobile Application."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  dartz: ^0.10.1
  dio: ^5.4.3+1
  intl: ^0.19.0
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  logger: ^2.3.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  oktoast: ^3.4.0
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  dot_navigation_bar: ^1.0.2
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  text_area: ^0.0.3
  easy_search_bar: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  icons_launcher: ^2.1.7
  isar_generator: ^3.1.0+1
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.6.0

flutter_gen:
  output: lib/core/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/bg/
    - assets/images/hero/
    - assets/images/tactical-board/
    - assets/images/exam/
    
